### ISSUE TITLE
transformer

### ISSUE THREAD

**Issue by mcer12** [waicool20/Divergence-Meter-Project-v2#1]
Hi, great project! I wanted to make one but the BOM is kinda vague. The most crucial part is the transformer, you only provide type but not what particular model (properties) is needed. Could you elaborate on that?

**Comment by waicool20** [comment]
I used the TTRN-0530H-044-T, 11:1 turn ratio, [datasheets should be here](https://www.tokyocoil.com/wp-content/themes/tokyo_coil/pdf/ttrn/TTRN-0530H.pdf) Particular model (044-T part) shouldn't really matter I believe IIRC

Just a note that this project is in a incomplete state, as shown by the lack of progress on the software side of things. As it is, it only displays the current time stored in the RTC with no way to set or unset settings etc. 

For now the project will remain in an indefinite hiatus for personal reasons

**Comment by mcer12** [comment]
@waicool20 thank you for the reply, I was in a process of ordering components so you stopped me just in time :D I'm worried about different properties - inductance, turns ratio of different models - which I expect would need adjustments of the design which I don't have the tools to properly test. The particular model TTRN-0530H-044-T doesn't seem to be available anywhere except taobao which is too foreign for me :( 
Since the project is on ice, maybe I can use the booster design alone, which is super simple and elegant by the way! I've seen this project which uses same switcher but different transformer and slightly different components:
https://www.pcbway.com/project/shareproject/LM3481_high_efficiency_transformer_glow_tube_booster_module.html
but there's very little information about it, maximum current delivery for example.

**Comment by waicool20** [comment]
I've not done a lot of testing on current capabilities but it is able to power the 8 tubes at max brightness down to about [3.5V](http://3.5v/) on the [4.2V](http://4.2v/) 10000 mAh li ion cells for a whole day, I havnt figured out how to extract the remaining [0.3V](http://0.3v/) or so on the discharge curve yet tho. 

The project you linked has basically the same design which I kind of expected, [TI writes good guidelines on how to use their products](https://www.ti.com/lit/an/snva761a/snva761a.pdf), the only major difference in TIs design is that they use an optocoupler to have full input-output isolation, they also have a lot of extra components to enhance the performance of the circuit, which the project you linked + the one used here mostly omitted due to size driven requirements. Max output current is mostly driven by the selected components, basically if you scale the components up (eg. battery, transformer, mosfet) you can probably increase the current output, but again due to size requirements this is not always the case.

You can get those transformers off of [AliExpress](https://m.aliexpress.com/item/4001298751715.html?gatewayAdapt=Pc2Msite) which should be more accessible, this one is a slightly different model but should work just fine, you can also modify the footprint to fit any other high turn ratio transformer that are available to you.

The specific inductance of the transformers is not as crucial as we're not really powering anything very precise, nixie tubes look elegant but they are pretty crude devices functionally, so power quality is not on the top of the priority list. I wouldn't use the boost circuit for high accuracy applications.

The transformer also heats up quite a bit due to its small size which affects its power delivery capabilities, I think a passive heatsink is needed to achieve better performance.

**Comment by mcer12** [comment]
Thank you very much. I will probably merge the two of your designs together, because TTRN-060s-013-T is cheaply available on Ali as I happend to find and it should have higher maximum current so it should run colder. Thank you so much for the clarifications and hope I didn't bother too much with the dumb questions :) I'll reopen the issue in case something else comes up.
